services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-8.2}-v4-cli
    environment:
      TYPO3_VERSION: ${TYPO3_VERSION:-^12.4}
      TYPO3_API_TOKEN:
      TYPO3_API_PASSWORD:
      TYPO3_API_USERNAME:
      TAG:
      typo3DatabaseHost: mysql
      typo3DatabaseName: typo3
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
      ELASTICSEARCH_HOST: elasticsearch:9200
      PHP_EXTENSIONS: gd intl
      HTTP_HOST: dummy
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app

  mysql:
    image: mysql:8.0
    command:
      - mysqld
      - --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/lib/mysql

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION:-7.17.22}
    environment:
      - "ES_JAVA_OPTS=-Xms1m -Xmx4096m"
      - ingest.geoip.downloader.enabled=false
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl --silent http://localhost:9200/_cluster/health | grep --quiet '\"status\":\"\\(green\\|yellow\\)\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
